services:
  migrator:
    build:
      context: .
    image: adventuria:2.0.0
    pull_policy: never
    command: [ "./adventuria", "migrate", "up" ]
    working_dir: /adventuria
    restart: "no"
    volumes:
      - pb_data:/adventuria/pb_data

  api:
    image: adventuria:2.0.0
    pull_policy: never
    depends_on:
      migrator:
        condition: service_completed_successfully
    command: [ "./adventuria", "serve", "--http=0.0.0.0:8080" ]
    working_dir: /adventuria
    ports:
      - "8080:8080"
    volumes:
      - pb_data:/adventuria/pb_data

volumes:
  pb_data: { }
